/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sharedFileAndFolder;

import java.io.File;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import peerManage.UserDetails;
import serialds.DSHandle;

/**
 *
 * @author satyam
 */
public class FileAndFolerChooser extends javax.swing.JFrame {
    UserDetails userDetails;
    /**
     * Creates new form FileAndFolerChooser
     */
    public FileAndFolerChooser(UserDetails userDetails){
        initComponents();
        this.userDetails=userDetails;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listOfFiles = new javax.swing.JList<>();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Files to Share");

        listOfFiles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listOfFiles.setModel(new DefaultListModel<String>());
        jScrollPane1.setViewportView(listOfFiles);

        addButton.setText("Add New File/Folder(s)");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove Selected File/Folder(s)");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Update File Share List");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(removeButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addGap(38, 38, 38)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        JFileChooser fc=new JFileChooser();
        File f=new File(System.getProperty("user.home"));
        fc.setCurrentDirectory(f);
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = fc.showOpenDialog(this);
        File file;
        DefaultListModel dlm=(DefaultListModel) listOfFiles.getModel();
        if(dlm==null)
                dlm=new DefaultListModel();
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
            dlm.addElement(file.getPath());
            listOfFiles.setModel(dlm);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        DefaultListModel dlm=(DefaultListModel)listOfFiles.getModel();
        int ind=listOfFiles.getSelectedIndex();
        dlm.removeElementAt(ind);
        listOfFiles.setModel(dlm);
        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Queue<File> shfnfo=new LinkedList<File>();
        DefaultListModel dlm=(DefaultListModel)listOfFiles.getModel();
        int to=dlm.getSize();
        for(int i=0;i<to;i++) {
            shfnfo.add(new File( (String) dlm.getElementAt(i)));
        }
        FileFetcher obj = new FileFetcher(shfnfo);
        DSHandle DSobj=obj.getFiles();
        userDetails.shareFileNfolder=DSobj;
        System.out.println("DSHANDLE object made");
//        for(int i=0;i<shareFileAndFolder.v.size();i++){
//            for(int j=0;j<shareFileAndFolder.v.get(i).size();j++){
//                if(shareFileAndFolder.v.get(i).get(j).name.contains("gym"))
//                System.out.println(shareFileAndFolder.v.get(i).get(j).name);
//            }
//        }

    //sending object to server
    
        try{
            Socket sock = new Socket(userDetails.serverIP,3002);
            ObjectOutputStream oos = new ObjectOutputStream(sock.getOutputStream());
            oos.writeObject(DSobj);
            //ds.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        } 
        System.out.println("shared file n folder!");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listOfFiles;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
